# action.yml
name: 'Qovery deploy'
description: 'Deploy on your Qovery projects'
author: Qovery <support@qovery.com>

branding:
  icon: "upload-cloud"
  color: "purple"

inputs:
  qovery-api-token:
    description: 'Qovery API token'
    required: false
  qovery-organization-id:
    description: 'Qovery organization ID'
    required: false
  qovery-organization-name:
    description: 'Qovery organization name'
    required: false
  qovery-project-id:
    description: 'Qovery project ID'
    required: false
  qovery-project-name:
    description: 'Qovery project name'
    required: false
  qovery-environment-id:
    description: 'Qovery environment ID'
    required: false
  qovery-environment-name:
    description: 'Qovery environment name'
    required: false
  qovery-application-ids:
    description: 'Qovery application IDS'
    required: false
  qovery-application-commit-id:
    description: 'Qovery app commit id'
    required: false
  qovery-application-names:
    description: 'Qovery application names'
    required: false
  qovery-database-id:
    description: 'Qovery database ID'
    required: false
  qovery-database-name:
    description: 'Qovery database name'
    required: false
  qovery-container-ids:
    description: 'Qovery container IDs, separated by `,`'
    required: false
  qovery-container-names:
    description: 'Qovery container names, separated by `,`'
    required: false
  qovery-container-tags:
    description: 'Qovery container tags, separated by `,`'
    required: false
outputs:
  environment-state:
    description: 'Environment state on which app has been deployed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --org-id=${{ inputs.qovery-organization-id }}
    - --org-name=${{ inputs.qovery-organization-name }}
    - --project-id=${{ inputs.qovery-project-id }}
    - --project-name=${{ inputs.qovery-project-name }}
    - --env-id=${{ inputs.qovery-environment-id }}
    - --env-name=${{ inputs.qovery-environment-name }}
    - --app-ids=${{ inputs.qovery-application-ids }}
    - --app-names=${{ inputs.qovery-application-names }}
    - --app-commit-id=${{ inputs.qovery-application-commit-id }}
    - --db-id=${{ inputs.qovery-database-id }}
    - --db-name=${{ inputs.qovery-database-name }}
    - --container-ids=${{ inputs.qovery-container-ids }}
    - --container-names=${{ inputs.qovery-container-names }}
    - --container-tags=${{ inputs.qovery-container-tags }}
    - --api-token=${{ inputs.qovery-api-token }}
